### ISSUE TITLE
Setting up PyTorch plugin "gridsample_grad2"... Failed!

### ISSUE THREAD

**Issue by YunnaChen** [yiqun-wang/PET-NeuS#9]
Hi I meet this trouble， the problem is list below:
Setting up PyTorch plugin "gridsample_grad2"... Failed!
Traceback (most recent call last):
  File "/home/anaconda3/envs/Neus/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1673, in _run_ninja_build
    env=env)
  File "/home/anaconda3/envs/Neus/lib/python3.7/subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "./exp_runner_pet.py", line 19, in <module>
    from models.triplane_pet import TriPlaneGenerator
  File "/mnt/hdd2/code/PET-NeuS/models/triplane_pet.py", line 7, in <module>
    from third_party.ops import grid_sample
  File "/mnt/hdd2/code/PET-NeuS/third_party/ops/grid_sample.py", line 26, in <module>
    _init()
  File "/mnt/hdd2/code/PET-NeuS/third_party/ops/grid_sample.py", line 22, in _init
    extra_cuda_cflags=['--use_fast_math'],
  File "/mnt/hdd2/code/PET-NeuS/third_party/custom_ops.py", line 139, in get_plugin
    verbose=verbose_build, sources=cached_sources, **build_kwargs)
  File "/home/anaconda3/envs/Neus/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1091, in load
    keep_intermediates=keep_intermediates)
  File "/home/anaconda3/envs/Neus/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1302, in _jit_compile
    is_standalone=is_standalone)
  File "/home/anaconda3/envs/Neus/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1407, in _write_ninja_file_and_build_library
    error_prefix=f"Error building extension '{name}'")
  File "/home/anaconda3/envs/Neus/lib/python3.7/site-packages/torch/utils/cpp_extension.py", line 1683, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'gridsample_grad2': [1/2] /usr/local/cuda-11.2/bin/nvcc --generate-dependencies-with-compile --dependency-output gridsample_cuda.cuda.o.d -DTORCH_EXTENSION_NAME=gridsample_grad2 -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /home/anaconda3/envs/Neus/lib/python3.7/site-packages/torch/include -isystem /home/anaconda3/envs/Neus/lib/python3.7/site-packages/torch/include/torch/csrc/api/include -isystem /home/anaconda3/envs/Neus/lib/python3.7/site-packages/torch/include/TH -isystem /home/anaconda3/envs/Neus/lib/python3.7/site-packages/torch/include/THC -isystem /usr/local/cuda-11.2/include -isystem /home/anaconda3/envs/Neus/include/python3.7m -D_GLIBCXX_USE_CXX11_ABI=0 -D__CUDA_NO_HALF_OPERATORS__ -D__CUDA_NO_HALF_CONVERSIONS__ -D__CUDA_NO_BFLOAT16_CONVERSIONS__ -D__CUDA_NO_HALF2_OPERATORS__

**Comment by SWWdz** [comment]
I also get this problem, do you solve it?

**Comment by YunnaChen** [comment]
> 
I use 11.3 CUDA version, it works.

**Comment by SWWdz** [comment]
Thanks! I will have a try.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "yiqun-wang/PET-NeuS"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月24日(星期四) 上午10:15
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [yiqun-wang/PET-NeuS] Setting up PyTorch plugin "gridsample_grad2"... Failed! (Issue #9)





   
I use 11.3 CUDA version, it works.
